[package]
name = "bitpacker"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
regex = "1.10.3"

[dev-dependencies]
trybuild = "1.0"

[lib]
proc-macro = true
